#!/bin/bash
# Quick Testing Guide for MockTrade Changes

echo "=========================================="
echo "MockTrade - Testing Guide"
echo "=========================================="
echo ""
echo "CHANGES IMPLEMENTED:"
echo "1. ✅ Trader dropdown in Order Entry (fetches from Static Data)"
echo "2. ✅ Trade Module with Cancel/Expire functionality"
echo "3. ✅ All backend tables created and in place"
echo "4. ✅ Full CRUD operations for all static data"
echo ""
echo "=========================================="
echo ""
echo "TO TEST - Run in this order:"
echo ""
echo "STEP 1: Start Backend"
echo "-------"
echo "cd /Users/ravikiranreddygajula/MockTrade/mock-trade-api"
echo ".venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"
echo ""
echo "STEP 2: Start Frontend (new terminal)"
echo "--------"
echo "cd /Users/ravikiranreddygajula/MockTrade/mock-trade-ui"
echo "npm run dev"
echo ""
echo "STEP 3: Open Browser"
echo "--------"
echo "Navigate to: http://localhost:5173"
echo ""
echo "=========================================="
echo "TESTING SEQUENCE:"
echo "=========================================="
echo ""
echo "TEST 1: Create Traders in Static Data"
echo "1. Click 'Static Data' module"
echo "2. Click 'Traders' tab"
echo "3. Click 'New Entry' button"
echo "4. Enter:"
echo "   User ID: TRADER001"
echo "   Name: Alice Trader"
echo "   Desk: FX"
echo "5. Click 'Create trader'"
echo "6. Repeat for TRADER002, TRADER003"
echo ""
echo "TEST 2: Create Instruments in Static Data"
echo "1. Click 'Instruments' tab"
echo "2. Click 'New Entry'"
echo "3. Enter:"
echo "   Symbol: ES"
echo "   Name: E-mini S&P 500"
echo "   Asset Class: INDEX"
echo "   Type: FUTURE"
echo "4. Click 'Create instrument'"
echo "5. Repeat for NQ, EURUSD"
echo ""
echo "TEST 3: Order Entry with Trader Dropdown"
echo "1. Click 'Order Entry' module"
echo "2. Verify 'Trader' field is now a DROPDOWN (not text)"
echo "3. Click dropdown - should show TRADER001, TRADER002, TRADER003"
echo "4. Select TRADER001"
echo "5. Fill other fields (Instrument: ES, Side: BUY, etc.)"
echo "6. Click 'Create' - order should be created with trader"
echo ""
echo "TEST 4: Trade Module"
echo "1. Click 'Trade Module' from left sidebar"
echo "2. Should show list of trades (if any exist)"
echo "3. Filter by Status (Filled, Active, etc.)"
echo "4. For any ACTIVE trade row:"
echo "   - See 'Cancel' and 'Expire' buttons"
echo "   - Click Cancel - should prompt for confirmation"
echo "   - Trade status should change to CANCELLED"
echo "5. Click any trade row to see details panel on right"
echo "6. Action buttons appear in details panel too"
echo ""
echo "TEST 5: Create/Edit/Delete Brokers & Clearers"
echo "1. Go to Static Data -> Brokers"
echo "2. Create a broker (code: BR001, name: Goldman Sachs)"
echo "3. Click 'Edit' button - form should populate"
echo "4. Click 'Delete' button - should prompt for confirmation"
echo "5. Repeat for Clearers"
echo ""
echo "=========================================="
echo "EXPECTED RESULTS:"
echo "=========================================="
echo ""
echo "✅ No 'Cannot reach API' errors"
echo "✅ Traders dropdown in Order Entry populated from Static Data"
echo "✅ Trade Module displays all trades"
echo "✅ Cancel/Expire buttons work (change status)"
echo "✅ All CRUD operations (Create/Edit/Delete) work"
echo "✅ Filters work (status, instrument, trader)"
echo "✅ Trade details panel shows on selection"
echo ""
echo "=========================================="
echo ""
echo "If any test fails, check:"
echo "1. Backend is running: curl http://127.0.0.1:8000/health"
echo "2. Frontend has no compile errors: npm run dev output"
echo "3. Database has tables: Check app.db file"
echo "4. API endpoints respond: curl http://127.0.0.1:8000/api/v1/trades/"
echo ""

