"""Fix account table

Revision ID: 5347d3a259a0
Revises: 81e9b75ad462
Create Date: 2025-10-16 12:38:07.588252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5347d3a259a0'
down_revision: Union[str, Sequence[str], None] = '81e9b75ad462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement_price')
    op.drop_table('position_daily')
    op.drop_table('audit_log')
    op.drop_table('variation_margin')
    op.drop_table('broker')
    op.drop_table('trader')
    op.drop_table('trade_allocation')
    op.drop_table('final_settlement_price')
    op.drop_table('eod_pnl')
    op.create_index(op.f('ix_account_account_id'), 'account', ['account_id'], unique=False)
    op.drop_column('account', 'code')
    op.alter_column('instrument', 'tick_size',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('instrument', 'tick_value',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_instrument_instrument_id'), 'instrument', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_order_hdr_order_id'), 'order_hdr', ['order_id'], unique=False)
    op.drop_constraint(op.f('order_hdr_trader_id_fkey'), 'order_hdr', type_='foreignkey')
    op.drop_constraint(op.f('order_hdr_account_id_fkey'), 'order_hdr', type_='foreignkey')
    op.create_index(op.f('ix_trade_hdr_trade_id'), 'trade_hdr', ['trade_id'], unique=False)
    op.drop_constraint(op.f('trade_hdr_trader_id_fkey'), 'trade_hdr', type_='foreignkey')
    op.drop_constraint(op.f('trade_hdr_broker_id_fkey'), 'trade_hdr', type_='foreignkey')
    op.drop_constraint(op.f('trade_hdr_account_id_fkey'), 'trade_hdr', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('trade_hdr_account_id_fkey'), 'trade_hdr', 'account', ['account_id'], ['account_id'])
    op.create_foreign_key(op.f('trade_hdr_broker_id_fkey'), 'trade_hdr', 'broker', ['broker_id'], ['broker_id'])
    op.create_foreign_key(op.f('trade_hdr_trader_id_fkey'), 'trade_hdr', 'trader', ['trader_id'], ['trader_id'])
    op.drop_index(op.f('ix_trade_hdr_trade_id'), table_name='trade_hdr')
    op.create_foreign_key(op.f('order_hdr_account_id_fkey'), 'order_hdr', 'account', ['account_id'], ['account_id'])
    op.create_foreign_key(op.f('order_hdr_trader_id_fkey'), 'order_hdr', 'trader', ['trader_id'], ['trader_id'])
    op.drop_index(op.f('ix_order_hdr_order_id'), table_name='order_hdr')
    op.drop_index(op.f('ix_instrument_instrument_id'), table_name='instrument')
    op.alter_column('instrument', 'tick_value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('instrument', 'tick_size',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.add_column('account', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_account_account_id'), table_name='account')
    op.create_table('eod_pnl',
    sa.Column('instrument_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('val_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('realized_pnl', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('unrealized_pnl', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('total_pnl', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], name=op.f('eod_pnl_account_id_fkey')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], name=op.f('eod_pnl_instrument_id_fkey')),
    sa.PrimaryKeyConstraint('instrument_id', 'account_id', 'val_date', name=op.f('eod_pnl_pkey'))
    )
    op.create_table('final_settlement_price',
    sa.Column('instrument_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('val_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('final_price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], name=op.f('final_settlement_price_instrument_id_fkey')),
    sa.PrimaryKeyConstraint('instrument_id', 'val_date', name=op.f('final_settlement_price_pkey'))
    )
    op.create_table('trade_allocation',
    sa.Column('allocation_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trade_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('alloc_qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], name=op.f('trade_allocation_account_id_fkey')),
    sa.ForeignKeyConstraint(['trade_id'], ['trade_hdr.trade_id'], name=op.f('trade_allocation_trade_id_fkey')),
    sa.PrimaryKeyConstraint('allocation_id', name=op.f('trade_allocation_pkey'))
    )
    op.create_table('trader',
    sa.Column('trader_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('desk', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('trader_id', name=op.f('trader_pkey'))
    )
    op.create_table('broker',
    sa.Column('broker_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('broker_id', name=op.f('broker_pkey'))
    )
    op.create_table('variation_margin',
    sa.Column('vm_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instrument_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('val_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('prev_settle', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('today_settle', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('net_qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contract_multiplier', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vm_amount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], name=op.f('variation_margin_account_id_fkey')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], name=op.f('variation_margin_instrument_id_fkey')),
    sa.PrimaryKeyConstraint('vm_id', name=op.f('variation_margin_pkey'))
    )
    op.create_table('audit_log',
    sa.Column('audit_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('audit_log_pkey'))
    )
    op.create_table('position_daily',
    sa.Column('instrument_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('val_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('net_qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('open_qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('close_qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], name=op.f('position_daily_account_id_fkey')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], name=op.f('position_daily_instrument_id_fkey')),
    sa.PrimaryKeyConstraint('instrument_id', 'account_id', 'val_date', name=op.f('position_daily_pkey'))
    )
    op.create_table('settlement_price',
    sa.Column('instrument_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('val_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('settle_price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], name=op.f('settlement_price_instrument_id_fkey')),
    sa.PrimaryKeyConstraint('instrument_id', 'val_date', name=op.f('settlement_price_pkey'))
    )
    # ### end Alembic commands ###
