"""add_trade_table

Revision ID: 93d7bc0a2260
Revises: 5347d3a259a0
Create Date: 2025-12-16 14:15:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93d7bc0a2260'
down_revision = '5347d3a259a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade',
        sa.Column('trade_id', sa.String(), nullable=False),
        sa.Column('order_id', sa.String(), nullable=True),
        sa.Column('instrument_id', sa.String(), nullable=True),
        sa.Column('side', sa.String(), nullable=True),
        sa.Column('qty', sa.Integer(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('exec_time', sa.DateTime(), nullable=True),
        sa.Column('trader_id', sa.String(), nullable=True),
        sa.Column('broker_id', sa.String(), nullable=True),
        sa.Column('account_id', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('cancellation_reason', sa.String(), nullable=True),
        sa.Column('expiry_date', sa.DateTime(), nullable=True),
        sa.Column('notional_value', sa.Float(), nullable=True),
        sa.Column('commission', sa.Float(), nullable=True),
        sa.Column('pnl', sa.Float(), nullable=True),
        sa.Column('unrealized_pnl', sa.Float(), nullable=True),
        sa.Column('trade_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
        sa.ForeignKeyConstraint(['broker_id'], ['broker.broker_id'], ),
        sa.ForeignKeyConstraint(['instrument_id'], ['instrument.instrument_id'], ),
        sa.ForeignKeyConstraint(['order_id'], ['order_hdr.order_id'], ),
        sa.ForeignKeyConstraint(['trader_id'], ['trader.trader_id'], ),
        sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_index(op.f('ix_trade_trade_id'), 'trade', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_trade_id'), table_name='trade')
    op.drop_table('trade')
    # ### end Alembic commands ###